os: linux
language: cpp
compiler: g++

jobs:
  include:
    - os: linux
      dist: focal
    - os: linux
      dist: bionic

notifications:
  email:
    recipients:
      - arturo.laurenzi@iit.it
    on_success: never
    on_failure: always

before_script:

# apt update and core packages installation
- sudo apt-get update
- sudo apt-get install git libgtest-dev cmake doxygen curl libboost-system-dev libboost-program-options-dev

# ROS source.list and keys
- sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
- curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -

- >
  if [[ `lsb_release -cs` == "focal" ]]; then 
      
      # ROS and Gazebo install
      sudo apt update && sudo apt install -y \
      ros-noetic-ros-base 

      . /opt/ros/noetic/setup.bash
 


  fi;

  if [[ `lsb_release -cs` == "bionic" ]]; then
  
      sudo apt update && sudo apt install -y \
      ros-melodic-ros-base

      . /opt/ros/melodic/setup.bash


  fi;



- sudo apt install ros-$ROS_DISTRO-urdf ros-$ROS_DISTRO-srdfdom ros-$ROS_DISTRO-kdl-parser 
- sudo apt install ros-$ROS_DISTRO-moveit-setup-assistant 
- source /opt/ros/$ROS_DISTRO/setup.bash

script: 
- set +e
- mkdir build
- cd build
- cmake ..
- make
